### ISSUE TITLE
Please provide a function to hide the annotation

### ISSUE THREAD

**Issue by georgehandrew** [lmk123/crx-selection-translate#1216]
## 功能简介
When selecting text with highlight/underline annotation, it's very hard to select the words accurately for further translation.
(Please try any pdf file with highlight/underline annotation. I used PDF Xchange Editor for example)
I reported this for pdf.js at:
https://github.com/mozilla/pdf.js/issues/14223
They don't seem to think it's very important, which I can understand, because for selecting text out, people have lots of choice on pdf readers. 
## 为什么你觉得需要（改进）这个功能？
But for a translation software as the internet browser extension, to select text is the basic function. So probably I think you are willing to improve this...
I noticed someone suggested the following solution in his own application.
https://github.com/mozilla/pdf.js/issues/7013#issuecomment-216370936
I am not sure whether it's the only solution or not, but just fyi.

Thanks a lot!

**Comment by lmk123** [comment]
> any pdf file with highlight/underline annotation.

Do you mean the link in the PDF file like this?

![image](https://user-images.githubusercontent.com/5035625/140100387-cf29bab4-74be-49e6-84ce-4cb56c232a3f.png)

If so, I can show you two ways to translate the text in the link.

If not, please provide me with a PDF file containing the highlight/underline annotations, preferably with a screenshot telling me exactly what you mean by highlight/underline annotations. I rarely read PDF files, so I'm not quite sure what you mean by highlight/underline annotations.

**Comment by georgehandrew** [comment]
Thank you for reply.
please try the attached file.
the underlined parts seem ok. You can select the text with the underline accurately.
But for the highlighted contests, things are different. For the first highlighted part, you can select accurately, but for the second one, you cannot. It is interesting and looks due to probably different software annotate with different methods.
I would suggest adding a function to switch hide/display the annotation in the software as a workaround, if possible.
I think this might be greatly helpful to lots of students who read pdfs a lot.
[j.cocis.2009.11.004_1.pdf](https://github.com/lmk123/crx-selection-translate/files/7486858/j.cocis.2009.11.004_1.pdf).

**Comment by lmk123** [comment]
I'm sorry it's taken me so long to get back to you, I've been busy with another more serious issue lately.

This problem could not be solved by me, because for the second highlighted part, PDF.js does not provide the text layer.

For the first highlighted part, it has a text layer, so its text can be selected normally:

<img width="937" alt="截屏2021-11-20 下午12 44 53" src="https://user-images.githubusercontent.com/5035625/142714785-b6ba8468-96e2-4555-a1fd-c86097db09e4.png">

But for the second one, it has no text layer, so no text can be selected:

<img width="920" alt="截屏2021-11-20 下午12 45 38" src="https://user-images.githubusercontent.com/5035625/142714817-754e788b-628e-497f-b059-1bd62cbb1ffd.png">
 
That is, the reason that the second highlighted part cannot be selected is because it does not have a text layer, which is generated by PDF.js. I cannot "inject" into PDF.js to make it generate a text layer for the second highlight part.

I suggest you use the screenshot translation (named "截图翻译") feature to translate this part of the text that cannot be selected, or wait until PDF.js provides a text layer and I'll figure it out.

**Comment by lmk123** [comment]
Since I can't solve this problem, I'll close this issue for now. I will see what I can do later when PDF.js generates the text layer for the annotation.

**Comment by georgehandrew** [comment]
> Since I can't solve this problem, I'll close this issue for now. I will see what I can do later when PDF.js generates the text layer for the annotation.

Hi lmk123,

thank you for reply.
